### ISSUE TITLE
Incluir a coluna token na tabela users

### ISSUE THREAD

**Issue by guuilp** [gubartz/IFSP-ServicosWS#1]
Gustavo, eu vi que você incluiu a coluna token na tabela usuarios para o uso do login no webservice, mas no .sql (dentro da pasta database), não possui isso. Quando possível, incluir a coluna token na tabela usuarios.

**Comment by gubartz** [comment]
Parece q vc substitui o sql antes de fazer um clone ou pull. Dá uma olhada e veja que o token estava lá https://github.com/gubartz/IFSP-ServicosWS/commit/cdf06e04ef3e7cbbd22fee8d93cf9bd82645e568

**Comment by gubartz** [comment]
Corrigido no commit 208aa93b9086756b8274da06f26e71b8b4edf373
